sudo: required

services:
  - docker

before_install:
  # Decrypt GCP service account file
  - openssl aes-256-cbc -K $encrypted_9112fb2807d4_key -iv $encrypted_9112fb2807d4_iv -in service-account.json.enc -out service-account.json -d

  # Install Google SDK and update kubectl
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components install kubectl

  # Activate the GCP service account and select the project, compute zone and cluster
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-fancyfib
  - gcloud config set compute/zone europe-west2-a
  - gcloud container clusters get-credentials multi-cluster

  # Login to Docker CLI, build test image
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t andystoica/client-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests
  - docker run -e CI=true andystoica/client-test npm run test
